# Generated by Django 3.0.4 on 2020-04-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UsernameOrTelephoneNumber', models.TextField()),
                ('Email', models.TextField()),
                ('productID', models.IntegerField()),
                ('Message', models.TextField()),
            ],
        ),
    ]
